version: 1.0.{build}

image: Visual Studio 2017
shallow_clone: true

init:
- ps: |+
    if($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_TAG_NAME.StartsWith("v") -eq $true) {
      Set-AppVeyorBuildVariable -Name APPVEYOR_BUILD_VERSION -Value $env:APPVEYOR_REPO_TAG_NAME.Substring(1)
    }

before_build:
- cmd: |+
    cd src
    msbuild /t:Restore
    cd ..

build:
  verbosity: minimal

after_build:
- cmd: |+
    cd Build 
    build-choco.cmd 
    cd ..

artifacts:
- path: '**/Release/choco/*.nupkg'
  name: ChocoPackage

deploy:
- provider: GitHub
  tag: v$(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: bupArXj8lz6RLLO8GPwyRnbGwcmyjg4MvmlBsYD8x+euC9YS5G5y9jaSPCpS7tsX
  artifact: ChocoPackage
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  server: https://chocolatey.org/
  api_key:
    secure: q2DB10LN/by6AA8S1RL/Kq8MDO7ZdO3YDKctDIWNf/MT3k9apusTKqKR0YahRw0a
  artifact: ChocoPackage
  on:
    APPVEYOR_REPO_TAG: true